### ISSUE TITLE
How to use this on the Criteo Terabyte Dataset?

### ISSUE THREAD

**Issue by csdingbin** [yanzhoupan/dlrm_ssm#1]
FYI. Reference your  @yanzhoupan code, I just see you only support the small dataset of " Criteo Kaggle Display Advertising Challenge Dataset". In the original Facebook DLRM repo they also support Criteo Terabyte Dataset. So will you also support this? And also could you tell me how to use lsh_pp_pretaining.py on Criteo Terabyte Dataset? Because the larger dataset for training almost 621GB after processed by data_utils.py, directly load whole file will OOM. Thanks!

**Comment by yanzhoupan** [comment]
Yes we did all the experiment on the smaller dataset. But we didn't modify the data processing part of the code. So you should be able to run the code with the larger dataset with very little change of the code. 

Currently lsh_pp_pretaining.py might not support you to load the whole terabyte dataset into memory, you can try to sample the datset before using lsh_pp_pretaining.py.
