### ISSUE TITLE
hashedEmbeddingBag CPU version code

### ISSUE THREAD

**Issue by csdingbin** [yanzhoupan/dlrm_ssm#2]
Do  you (@yanzhoupan) have hashedEmbeddingBag CPU version code?

**Comment by yanzhoupan** [comment]
Hi @csdingbin we do have a python script for CPU version hashedEmbeddingBag under /tricks folder. It's called hash_embedding_bag.py. It's kind of a test of hashedEmbeddingBag, not a very careful implementation.
